const provinces = [
  { code: "1", name: "黑龙江省" },
  { code: "2", name: "吉林省" },
  { code: "4", name: "辽宁省" },
  { code: "3", name: "湖南省" },
  { code: "5", name: "浙江省" },
  { code: "6", name: "安徽省" },
  { code: "7", name: "福建省" },
  { code: "42", name: "四川省"},
  { code: "9", name: "江西省" },
  { code: "10", name: "山西省" },
  { code: "11", name: "贵州省" },
  { code: "59", name: "青海省" },
  { code: "60", name: "山东省" },
  { code: "76", name: "广东省立中山" },
  { code: "13", name: "广西省" },
  { code: "61", name: "河北省" },
  { code: "62", name: "陕西省" },
  { code: "8", name: "湖北省" },
  { code: "86", name: "云南省图书馆" },
  { code: "84", name: "甘肃省图书馆" },
  { code: "85", name: "海南省图书馆" },
  { code: "87", name: "内蒙古自治区图书馆" },
  { code: "88", name: "西藏自治区图书馆" },
  { code: "45", name: "南京" },
  { code: "57", name: "新疆自治区" },
  { code: "58", name: "上海市" },
  { code: "38", name: "上海浦东" },
  { code: "41", name: "重庆市" },
  { code: "75", name: "天津市" },
  { code: "12", name: "成都市" },
  { code: "20", name: "广州市" },
  { code: "37", name: "深圳市" },
  { code: "27", name: "珠海市" },
  { code: "35", name: "东莞市" },
  { code: "14", name: "济南市" },
  { code: "15", name: "青岛市" },
  { code: "67", name: "烟台市" },
  { code: "68", name: "威海市" },
  { code: "89", name: "大连图书馆" },
  { code: "90", name: "沈阳市图书馆" },
  { code: "22", name: "武汉市" },
  { code: "63", name: "石家庄市图书馆" },
  { code: "64", name: "唐山市" },
  { code: "65", name: "保定市" },
  { code: "66", name: "秦皇岛市" },
  { code: "16", name: "杭州市" },
  { code: "69", name: "苏州市" },
  { code: "46", name: "西安市" },
  { code: "18", name: "厦门市" },
  { code: "29", name: "长沙市" },
  { code: "71", name: "合肥市" },
  { code: "73", name: "昆明市" },
  { code: "47", name: "哈尔滨市" },
  { code: "56", name: "三亚市" },
  { code: "44", name: "无锡市" },
  { code: "48", name: "扬州市" },
  { code: "50", name: "太原市" },
  { code: "52", name: "福州市" },
  { code: "55", name: "海口市" },
  { code: "43", name: "呼伦贝尔市" },
  { code: "51", name: "呼和浩特市" },
  { code: "54", name: "南宁市" },
  { code: "74", name: "宁夏回族自治区" },
  { code: "77", name: "北京首都" },
  { code: "78", name: "河南省" },
  { code: "79", name: "南京金陵" },
  { code: "31", name: "中山市" },
  { code: "39", name: "福泉市" },
  { code: "25", name: "绍兴市" },
  { code: "80", name: "南昌市" },
  { code: "81", name: "贵阳市" },
  { code: "82", name: "宁波市" },
  { code: "83", name: "国家" },//国家图书馆
  { code: "91", name: "郑州图书馆" },
  { code: "92", name: "泉州市图书馆" },
  { code: "93", name: "佛山市图书馆" },
  { code: "94", name: "南通市图书馆" },
  { code: "95", name: "常州市图书馆" },
  { code: "96", name: "徐州市图书馆" },
  { code: "97", name: "潍坊市图书馆" },
  { code: "98", name: "盐城市图书馆" },
  { code: "99", name: "长春市图书馆" },
  { code: "100", name: "嘉兴市图书馆" },
  { code: "101", name: "金华市图书馆" },
  { code: "102", name: "台州市图书馆" },
  { code: "103", name: "泰州市图书馆" },
  { code: "104", name: "临沂市图书馆" },
  { code: "105", name: "宜昌市图书馆" },
  { code: "106", name: "惠州慈云图书馆" },
  { code: "107", name: "榆林市图书馆" },
//{ code: "72", name: "黄石市" },
  // 
  // { code: "40", name: "来宾市" },
  // { code: "49", name: "镇江市" },
  // { code: "30", name: "晋城市" },
  // 
  // { code: "33", name: "莆田市" },
  // { code: "34", name: "江阴市" },
  // { code: "23", name: "铁岭市" },
  // { code: "24", name: "鄂州市" },
  // 
  // { code: "26", name: "百色市" },
  // { code: "21", name: "鞍山市" },
  // { code: "28", name: "张家港" },
  // { code: "19", name: "赤峰市" },
  // { code: "17", name: "株洲市" },
  // { code: "36", name: "柳州市" },
];

// 唯一的离线馆列表。联网时由 /api/libraries 刷新；其余页面不再维护副本。
globalThis.LIBRARIES = provinces;
  
